services:
  db_invoice:
    image: 'postgres:13.1-alpine'
    container_name: db_invoice
    environment:
      - POSTGRES_USER=compose-postgres
      - POSTGRES_PASSWORD=compose-postgres
    ports:
      - 5433:5432

  invoice_service:
    image: demo/invoice:latest
    build:
      context: ./invoice
    container_name: invoice
    depends_on:
      - db_invoice
    environment:
      - "SPRING_PROFILES_ACTIVE=dev"
    ports:
      - 8083:8083
    volumes:
      - invoices:/var/lib/invoices/data

  db_user:
    image: 'postgres:13.1-alpine'
    container_name: db_user
    environment:
      - POSTGRES_USER=compose-postgres
      - POSTGRES_PASSWORD=compose-postgres
    ports:
      - 5432:5432

  users_service:
    image: demo/service-users:latest
    build:
      context: ./service-users
    container_name: service-users
    depends_on:
      - db_user
    environment:
      - "SPRING_PROFILES_ACTIVE=dev"
    ports:
      - 8081:8081

  eureka-server:
    image: demo/eureka-server:latest
    container_name: eureka-server
    build:
      context: ./eureka-server
    environment:
      - "SPRING_PROFILES_ACTIVE=dev"
    ports:
      - "8761:8761"

  api-gateway:
    image: demo/api-gateway:latest
    container_name: api-gateway
    build:
      context: ./api-gateway
    environment:
      - "SPRING_PROFILES_ACTIVE=dev"
    ports:
      - "9090:9090"
    depends_on:
      - eureka-server

  keycloak:
    image: quay.io/keycloak/keycloak:18.0.2
    command:
      - start-dev
      - --import-realm
    ports:
      - "8080:8080"
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin

volumes:
  invoices:
